const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.gamepad,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{VectorX: 0},
	{VectorY: 0},
	{UpdatePhysics: 0},
	{Timer: 0},
	{Player: 0},
	{Solid: 0},
	{Keyboard: 0},
	{WorldBackground: 0},
	{JumpStrengthBar: 0},
	{JumpStrengthBarFrame: 0},
	{Smoke: 0},
	{Gamepad: 0},
	{Alive: 0},
	{Tween: 0},
	{TutorialText: 0},
	{WinningTrigger: 0},
	{CelebrationText: 0},
	{WorldForeground: 0},
	{Touch: 0},
	{FallingLeaves: 0},
	{Sine: 0},
	{Token: 0},
	{TheScore: 0},
	{Audio: 0},
	{JumpMaxHorizontalStrength: 0},
	{JumpMaxVerticalStrength: 0},
	{JumpHorizontalDrag: 0},
	{JumpVerticalDrag: 0},
	{MaxFallSpeed: 0},
	{CollisionPrecision: 0},
	{ScoreCount: 0},
	{CurrentJumpStrength: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Solid: class extends self.ITilemapInstance {},
	Keyboard: class extends self.IInstance {},
	WorldBackground: class extends self.ISpriteInstance {},
	JumpStrengthBar: class extends self.ITiledBackgroundInstance {},
	JumpStrengthBarFrame: class extends self.ISpriteInstance {},
	Smoke: class extends self.ISpriteInstance {},
	Gamepad: class extends self.IInstance {},
	TutorialText: class extends self.ISpriteFontInstance {},
	WinningTrigger: class extends self.ISpriteInstance {},
	CelebrationText: class extends self.ISpriteFontInstance {},
	WorldForeground: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	FallingLeaves: class extends self.IParticlesInstance {},
	Token: class extends self.ISpriteInstance {},
	TheScore: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}